drop schema if exists tests cascade ;

create schema if not exists tests;

create table if not exists tests.products (
    id integer generated by default as identity primary key,
    name varchar(100) unique not null,
    price numeric(16, 2) not null
);
