drop schema if exists chat cascade;
create schema if not exists chat;

create table if not exists chat.users (
--id bigserial primary key,
id bigint generated by default as identity primary key,
email varchar (255) unique,
password varchar(10)
);
